### ISSUE TITLE
Template compose.yaml for QFieldCloud

### ISSUE THREAD

**Issue by FabianRechsteiner** [opengisch/QFieldCloud#1009]
Hello QFieldCloud team,

I would like to run the QFieldCloud Docker image and have created the following compose.yaml so far:

```yaml
---
services:
  qfieldcloud:
    image: opengisch/qfieldcloud-app:latest # https://hub.docker.com/r/opengisch/qfieldcloud-app
    container_name: qfieldcloud
    ports:
      - 8000:8000
    volumes:
      - ./qfieldcloud_data:/usr/src/app
    restart: always

```
However, I’m not sure if I have configured all the necessary parameters correctly. Is there an official template for the compose.yaml file that includes all the required settings and configurations? 

Thank you in advance for your support!

Best regards,
Fabian
