### ISSUE TITLE
QGIS container is keeps crashing in production deployment

### ISSUE THREAD

**Issue by amitabhajana** [opengisch/qfieldcloud#441]
Hi,

I am first time trying to setup qfield cloud on my server, but whenever i am trying to run the docker-compose.yml file by docker-compose up command, i can see the qgis container is keep crashing at the startup by showing error 
```
qfield_qgis                    | QGIS built
qfield_qgis exited with code 0
```

this is the service written in docker-compose.yml file
```
qgis:
    build:
      context: ./docker-qgis
    tty: true
    container_name: qfield_qgis
    command: bash -c "echo QGIS built"
    logging: *default-logging
```
Can anyone pls help me on this
